### ISSUE TITLE
Running SushiSwapJS gets "ENS is not defined"

### ISSUE THREAD

**Issue by tanwaarpornthip** [bartjman/BoringFinance#2]
After connected to Metamaks, SushiSwapJS calls to the go() function returns this error.
```
sushiswap.js:103 Uncaught (in promise) ReferenceError: ENS is not defined
    at new SushiSwap (sushiswap.js:103)
    at go ((index):13)
SushiSwap @ sushiswap.js:103
go @ (index):13
async function (async)
go @ (index):10
onclick @ (index):37
```
![image](https://user-images.githubusercontent.com/7297301/93024711-90fc5b80-f622-11ea-8a6c-6957674eb94e.png)
Looking through the source code, the function "ENS" is not defined.

**Comment by boringcrypto** [comment]
Ah, yeah, added ens.js... if you load that first it should work...
https://github.com/bartjman/SushiSwapJs/blob/master/ens.js
